spring:
  application:
    name: spring-ai-demo
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          temperature: 0.7
          deployment-name: gpt-4o